version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container-2
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: