# ====== JARs / Packages ======
spark.jars                             /opt/spark/jars-extra/*
spark.jars.packages                    com.datastax.spark:spark-cassandra-connector_2.12:3.5.1,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5
spark.jars.repositories                https://repo1.maven.org/maven2,https://maven-central.storage-download.googleapis.com/maven2

# ====== MinIO / S3A ======
spark.hadoop.fs.s3a.impl               org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint           http://minio:9000
spark.hadoop.fs.s3a.access.key         minio
spark.hadoop.fs.s3a.secret.key         minio12345
spark.hadoop.fs.s3a.path.style.access  true
spark.hadoop.fs.s3a.connection.ssl.enabled false

# ====== Cassandra ======
spark.cassandra.connection.host        cassandra
spark.cassandra.connection.port        9042
spark.cassandra.output.consistency.level LOCAL_ONE

# ====== Streaming / Performance ======
spark.sql.shuffle.partitions           8
spark.streaming.backpressure.enabled   true
